//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class celulare
    {
        public double imei { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string antigocolabcel { get; set; }
        public string atualcolabcel { get; set; }
        public Nullable<System.DateTime> dtacompracel { get; set; }
        public string statuscel { get; set; }
        public string estadocel { get; set; }
        public string obscel { get; set; }
        public int idcel { get; set; }
    }
}
