//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionario
    {
        public Nullable<double> matricula { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string tipoct365 { get; set; }
        public string cargo { get; set; }
        public string setor { get; set; }
        public string gestor { get; set; }
        public string dtadmissao { get; set; }
        public string dtdemissao { get; set; }
        public string statad { get; set; }
        public string statjira { get; set; }
        public string statconflu { get; set; }
        public string statslack { get; set; }
        public string door { get; set; }
        public string ponto { get; set; }
        public string statusf { get; set; }
        public int idfunc { get; set; }
    }
}
