//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class linha
    {
        public string simcard { get; set; }
        public int numlinha { get; set; }
        public string operadora { get; set; }
        public string antigocolablinha { get; set; }
        public string atualcolablinha { get; set; }
        public string statuslinha { get; set; }
        public string obslinha { get; set; }
        public int idlin { get; set; }
    }
}
