//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque.Models
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class login
    {
        public int UserID { get; set; }

        [DisplayName("Usuário")]
        [Required(ErrorMessage = "Favor preencher o Campo Usuário.")]
        public string usuario { get; set; }

        [DisplayName("Senha")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Favor preencher o Campo Senha.")]
        public string senha { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
