//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstoqueInfraEntities : DbContext
    {
        public EstoqueInfraEntities()
            : base("name=EstoqueInfraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<celulare> celulares { get; set; }
        public virtual DbSet<funcionario> funcionarios { get; set; }
        public virtual DbSet<linha> linhas { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<maquina> maquinas { get; set; }
        public virtual DbSet<monitore> monitores { get; set; }
    }
}
