//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maquina
    {
        public short patrimonio { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string servtag { get; set; }
        public string tipo { get; set; }
        public string numserie { get; set; }
        public string statusd { get; set; }
        public string estadod { get; set; }
        public string procd { get; set; }
        public string memoriad { get; set; }
        public string hdd { get; set; }
        public string antcolab { get; set; }
        public string atualcolab { get; set; }
        public string observacao { get; set; }
        public string dtacompra { get; set; }
        public string dtatroca { get; set; }
        public int idmaq { get; set; }
    }
}
